### ISSUE TITLE
Cannot open .tar.gz file on Windows 10

### ISSUE THREAD

**Issue by dreinert95** [josephkingstone/keepnote#1]
I'm a beginner pentester and am just getting into everything. I'm trying to open a .tar.gz file built by another GitHub user but I cannot seem to unzip the file and open it in KeepNote. I have 7zip installed as well as KeepNote but I still cannot open the file. Per the course I'm taking, this is an effective note-keeping tool and repository. Is it easier to run Linux on a Virtual Machine and then open the file. Any and all help is greatly appreciated. 

[keep-note-2019-12-27.tar.gz](https://github.com/josephkingstone/keepnote/files/4069028/keep-note-2019-12-27.tar.gz)

**Comment by drunkrhin0** [comment]
On Windows:

1. Download and install 7-zip manager
2. Select the file
3. Open it in the manager
4. Extract it
5. You'll now have the same file but as .tar
6. Now extract the .tar file and you'll have an extracted folder you can open in keepnote

**Comment by dreinert95** [comment]
That worked perfectly. Thank you for the help!
