### ISSUE TITLE
My antivirus is giving constant threats to this file

### ISSUE THREAD

**Issue by DhruvDoshi** [josephkingstone/keepnote#2]

**Comment by drunkrhin0** [comment]
The notes contain commands used for cybersecurity/hacking which flags the anti-virus. The file is safe

@josephkingstone you can probably close this but maybe update the readme.md to reflect?

**Comment by DhruvDoshi** [comment]
Thanks for the response!
So I will further work on cloud-based systems only!! for this file

**Comment by josephkingstone** [comment]
Adding Notes about A/V.  Thank you for the feedback.
